/*
 * This Java source file was generated by the Gradle 'init' task.
 */


package edu.au.cc.gallery;
import edu.au.cc.gallery.tools.UserAdmin;
public class App {
    public String getGreeting() {
        return "Hello Mohammad.";
    }

    public static void main(String[] args) throws Exception {
 System.out.println(new App().getGreeting());
//  S3.demo();
//  DB.demo();
 UserAdmin ua = new UserAdmin();
    ua.mainMenu();
    }
}
